language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:fkrull/deadsnakes
    - sudo apt-get update
    - sudo apt-get -qq install gcc-5 g++-5 libstdc++-5-dev libcppunit-dev python3.4 unzip


install:
    - PATH=$PATH:`pwd`/
    - wget https://github.com/martine/ninja/archive/v1.6.0/ninja-linux.zip
    - unzip ninja-linux.zip
    - rm ninja-linux.zip

    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10

    - wget https://github.com/mesonbuild/meson/releases/download/0.26.0/meson_0.26.0.tar.gz
    - tar -xvf meson_0.26.0.tar.gz
    - cd meson-0.26.0
    - python3.4 install_meson.py --prefix /home/`whoami`/meson
    - cd ..
    - rm -rf meson-0.26.0 meson_0.26.0.tar.gz

script:
    - p=`pwd`
    - mkdir build
    - cd build
    - python3.4 /home/`whoami`/meson/bin/meson `echo $p`
    - ninja
    - ./unittests

deploy:
    provider: releases
    api_key:
        secure: g9jmOw9wYkPDlXJY42YYHaiN3VEmKgQWWHifGn2CP0yHVYfmYL2XUAh1mOG2dAO+2wTcyziD2steHMe3KVzh/uvutTZJTcPOkGS9xISLBTEHUvdAOC4s5AWIE15zlGZWKRKs0UUg9zKiuK8B1siMBe8uyA+tir3UzlgIG4S2zXc=
    file: 'dist/${impl}/package/libcpp-bitstring.so.deb'
    skip_cleanup: true
    on:
        tags: true
        all_branches: true
        repo: alexandernst/cpp-bitstring
