language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
    - sudo apt-get update
    - sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev libcppunit-dev
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
    - if [ `getconf LONG_BIT` -eq 64 ]; then impl="Release_x64"; else impl="Release_86"; fi
    - make CONF=${impl}
    - make test CONF=${impl} 2>&1 | if [ `grep "Failures" | wc -l` -ne 0 ]; then exit 1; else exit 0 ; fi
    - ./nbproject/Package-${impl}.bash
    - ls -laR dist

deploy:
    provider: releases
    api_key:
        secure: g9jmOw9wYkPDlXJY42YYHaiN3VEmKgQWWHifGn2CP0yHVYfmYL2XUAh1mOG2dAO+2wTcyziD2steHMe3KVzh/uvutTZJTcPOkGS9xISLBTEHUvdAOC4s5AWIE15zlGZWKRKs0UUg9zKiuK8B1siMBe8uyA+tir3UzlgIG4S2zXc=
    file: 'dist/${impl}/package/libcpp-bitstring.so.deb'
    skip_cleanup: true
    on:
        repo: alexandernst/cpp-bitstring
