language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
    - sudo apt-get update
    - sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev libcppunit-dev
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
    - make
    - make test | grep -q "OK (f)" || (exit 1)